server:
  port: 8082
  
spring:
  application.name: products-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/products_db
    username: root
    password:
  sql.init:
    mode: always
    platform: mysql
