server:
  port: 8082

spring:
  application:
    name: motelManagement-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/motel_management_db
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      platform: postgresql

logging:
  level:
    com.ubik.usermanagement: DEBUG
    org.springframework.r2dbc: DEBUG