spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payments
    username: payments_user
    password: payments_pass

  flyway:
    url: jdbc:postgresql://localhost:5432/payments
    user: payments_user
    password: payments_pass

logging:
  level:
    com.acme.payments: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG