server:
  port: 8081

spring:
  application:
    name: userManagement-service

  r2dbc:
    url: ${DB_R2DBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always
      platform: postgresql

  security:
    bcrypt:
      strength: 12  # Fuerza del hash para contraseñas

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # 1 día en milisegundos
